[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [
    "benchmarks"
]
python_files = [
    "benchmark_*",
    "benchmarks/conftest.py"
]
python_functions = [
    "benchmark_*",
    "test_*"
]
