- name: install basic requirements
  apt:
    pkg:
      - git
      - wget
      - gnupg2
      - htop

- name: install python3
  apt:
    pkg:
      - python3
      - python-is-python3
      - python3-pip
      - python3-venv
