- name: install basic requirements
  apt:
    pkg:
      - git
      - wget
      - gnupg2
  become: true

- name: install python3
  apt:
    pkg:
      - python3
      - python-is-python3
      - python3-pip
      - python3-venv
  become: true

- name: install kernel headers
  apt:
    pkg:
      - "linux-headers-{{ ansible_facts['kernel'] }}"
      - "linux-modules-extra-{{ ansible_facts['kernel'] }}"
  become: true

- name: install cuda
  include_tasks: install_cuda.yml
